model:
  name: diffusers
  model_id: stabilityai/stable-diffusion-3.5-medium
  device: cuda
  width: 512
  height: 512
  num_inference_steps: 20
  guidance_scale: 4.5
  dtype: float16
  enable_model_cpu_offload: true
